name: C/C++ CI

on: [push]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7]
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -G "Unix Makefiles"
    - name: build CanTp library
      run: cd build && make CanTp
    - name: build CanTp post-build configuration library
      run: cd build && make CanTp_PBcfg
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user -r requirements.txt
    - name: autosar tests
      run: cd build && python -m pytest ../test/autosar_sws_test.py
